### ISSUE TITLE
googleapis.auth.oauth2 : A Valid Token results an error:  Invalid input length 245

### ISSUE THREAD

**Issue by dikovmaxim** [googleapis/google-oauth-java-client#1125]
#### Environment details

1. com.google.api-client  2.7.0
2. OS type and version: Windows 10 64
3. Java version: Oracle openjdk 17

Got a token on front-end (flutter GoogleSignIn)
Token:
`eyJhbGciOiJSUzI1NiIsImtpZCI6IjVhYWZmNDdjMjFkMDZlMjY2Y2NlMzk1YjIxNDVjN2M2ZDQ3MzBlYTUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIyMDQ0NDc3NDkwMjYtN3Rqdmk5c2xqa3JqYm91b3IwNHI2OTcyb28wdHNpNzUuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiIyMDQ0NDc3NDkwMjYtNWxmbTdtYW5waDNzNm1iZms1ZTQ3N3FyNTZtOWdqYmQuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDEyNDM3MDc5MjQ1OTgwMDIzNjQiLCJlbWFpbCI6InRoZW5ldGhlcmhhY2tAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJNaXN0ZXIgTmV0aGVyIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0xsWVktWGJfTGQ2VFJzVXFnc3JVZU5tdXpwX3RpeTdOYk5aMFc1d1VFcHFRSUg3U1dwPXM5Ni1jIiwiZ2l2ZW5fbmFtZSI6Ik1pc3RlciIsImZhbWlseV9uYW1lIjoiTmV0aGVyIiwiaWF0IjoxNzI3MzAxNDY3LCJleHAiOjE3MjczMDUwNjd9.H7yhbbv365KVmltj6x6gb8JY6Yf97eYZ4Q3VUHCVSsSCzugIAh06gu3TvsKDzNbS7TVyajWRuxYdqcumCOgU1vYmmTtetfkLPpUYdHKTwJ6bT1M8kHbGnIkMNgPOBYr7AfU-bklin-fK-lbVdgGeIMdZwp_RO0MAYU7GyNfUxn-jMDzKn9RqiX2O5rc454cJI2mjF269BDctwCqfl54MwshJJ0jsg3BrD1_spIbVmDS1LfZN2Xt5F`

According to JWT Website, this is a legitimate token, everything should work

#### Code example

```java
    private static final String CLIENT_ID = "204447749026-5lfm7manph3s6mbfk5e477qr56m9gjbd.apps.googleusercontent.com"; 
    public static Map<String, Object> verifyAndExtractInfo(String idTokenString) throws Exception {
        // Create a GoogleIdTokenVerifier instance with HTTP transport and Jackson factory
        GoogleIdTokenVerifier verifier = new GoogleIdTokenVerifier.Builder(new NetHttpTransport(), JacksonFactory.getDefaultInstance())
                .setAudience(Collections.singletonList(CLIENT_ID))  // Set the audience to your client ID
                .build();

        // Verify the token using the verifier
        GoogleIdToken idToken = verifier.verify(idTokenString); //tried to hardcode the string, didnt work, throws an error

        if (idToken == null) {
            throw new Exception("Invalid Google ID Token");
        }

        // Extract the payload from the verified token
        GoogleIdToken.Payload payload = idToken.getPayload();

        // Extract necessary information (e.g., user ID, email, name, etc.)
        String userId = payload.getSubject();  // Google User ID
        String email = payload.getEmail();
        String name = (String) payload.get("name");
        String pictureUrl = (String) payload.get("picture");

        // Return the extracted information as a map
        return Map.of(
                "userId", userId,
                "email", email,
                "name", name,
                "picture", pictureUrl
        );
    }
```

#### Stack trace
```
java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 245
	at com.google.common.io.BaseEncoding.decode(BaseEncoding.java:222)
	at com.google.api.client.util.Base64.decodeBase64(Base64.java:116)
	at com.google.api.client.json.webtoken.JsonWebSignature$Parser.parse(JsonWebSignature.java:551)
	at com.google.api.client.googleapis.auth.oauth2.GoogleIdToken.parse(GoogleIdToken.java:53)
	at com.google.api.client.googleapis.auth.oauth2.GoogleIdTokenVerifier.verify(GoogleIdTokenVerifier.java:187)
	at at.dikov.pinpalsserver.Services.GoogleAuthService.verifyAndExtractInfo(GoogleAuthService.java:27)
	at at.dikov.pinpalsserver.Controllers.AuthController.verifyToken(AuthController.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:110)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:108)
	at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:365)
	at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at at.dikov.pinpalsserver.Configs.JwtAuthenticationFilter.doFilterInternal(JwtAuthenticationFilter.java:51)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82)
	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
	at org.springframework.web.servlet.handler.HandlerMappingIntrospector.lambda$createCacheFilter$3(HandlerMappingIntrospector.java:195)
	at org.springframework.web.filter.CompositeFilter$VirtualFilterChain.doFilter(CompositeFilter.java:113)
	at org.springframework.web.filter.CompositeFilter.doFilter(CompositeFilter.java:74)
	at org.springframework.security.config.annotation.web.configuration.WebMvcSecurityConfiguration$CompositeFilterChainProxy.doFilter(WebMvcSecurityConfiguration.java:230)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:384)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 245
	at com.google.common.io.BaseEncoding$Base64Encoding.decodeTo(BaseEncoding.java:1033)
	at com.google.common.io.BaseEncoding$SeparatedBaseEncoding.decodeTo(BaseEncoding.java:1206)
	at com.google.common.io.BaseEncoding.decodeChecked(BaseEncoding.java:237)
	at com.google.common.io.BaseEncoding.decode(BaseEncoding.java:220)
	... 110 more
```

#### Any additional information below
It returns: invalid length 245, exactly the length of the signature section of the token.

Also, passing this token to` https://oauth2.googleapis.com/tokeninfo?id_token=` returns an error
Sorry, if this question is silly, but i havent found ANY information on it online, so thx for  helping in advice!

**Comment by lqiu96** [comment]
Thanks @dikovmaxim for reporting this! Just wanted to follow up and ask if this is still an issue on your end or if you were able to resolve this?

If not, I wanted to figure out how you're getting the ID Token String that you've pasted above. Unfortunately, the tokeninfo url doesn't work for expired tokens so I can't see if it's valid. 

Taking a look at the stacktrace, we see that it is complaining about the input length. Guava does a check to ensure that the token's padding is correct: https://github.com/google/guava/blob/d25d62fc843ece1c3866859bc8639b815093eac8/guava/src/com/google/common/io/BaseEncoding.java#L757-L759

I'm not too familiar with what *may* be wrong with the id token, but my assumption is that there may be something slightly off causing a padding issue. Were you following a GCP guide that led you to this issue or something that we can repro to generate a similar id token?

**Comment by dikovmaxim** [comment]
Hi. It's been a while...
Unfortunately, I cannot fully recall how fixed it (the project was paused, then rewritten again).
I remember getting away from the Java API and writing a manual service, which checked the token with the Google rest API request manually. (Which is why this package has under the hood I guess).
Interestingly, now tokens generated by Google are NOT seen as valid tokens of jwt, but are, as mentioned, working with Google manual requests, so I guess no other solution. Idk. Sorry for not being able to clarify further...

**Comment by lqiu96** [comment]
Glad to hear that you were able to resolve it (potentially from a rewrite due to us, sorry!). No worries about not remembering, this is an issue from way back.

> Interestingly, now tokens generated by Google are NOT seen as valid tokens of jwt

I'm not too sure I follow this part. Our Id Tokens are supposed to be valid JWTs (https://cloud.google.com/docs/authentication/token-types). Granted this is in the older oauth library that is not actively maintained, so it would not surprise me if there are new issues that have come up with Id Tokens. The new [auth library](https://github.com/googleapis/google-auth-library-java) *should* be handling this properly as a JWT.

Going to close this issue, but feel free to re-open this issue if this comes up again.
