### ISSUE TITLE
com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request

### ISSUE THREAD

**Issue by mahichachra** [googleapis/google-oauth-java-client#602]
getting this error

Exception in thread "main" com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
POST https://oauth2.googleapis.com/token
{
  "error" : "invalid_scope",
  "error_description" : "Invalid OAuth scope or ID token audience provided."
}
	at com.google.api.client.auth.oauth2.TokenResponseException.from(TokenResponseException.java:105)
	at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:326)
	at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:346)

Code snippet
public static Compute createComputeService() throws IOException, GeneralSecurityException {
        logger.info("Entered createComputeService");
        HttpTransport httpTransport = GoogleNetHttpTransport.newTrustedTransport();
        JsonFactory jsonFactory = JacksonFactory.getDefaultInstance();
        GoogleCredential credentials = GoogleCredential.getApplicationDefault();
        return new Compute.Builder(httpTransport, jsonFactory, credentials)
                .setApplicationName("Google-xyz/0.1")
                .build();
    }

**Comment by jbhushan791** [comment]
Is it resoved?

**Comment by jbhushan791** [comment]
It got resolved by setting scope

**Comment by roma2341** [comment]
> It got resolved by setting scope

what scope ?

**Comment by lqiu96** [comment]
For GoogleCredential, you can manually set the scopes via the [createScoped()](https://github.com/googleapis/google-api-java-client/blob/57882adbe0b9c48513642cfe624bb1ac7b842743/google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleCredential.java#L480-L485) call.

We have some javadocs [here](https://github.com/googleapis/google-api-java-client/blob/57882adbe0b9c48513642cfe624bb1ac7b842743/google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleCredential.java#L97-L133) that can how to manually add scopes (not using `createdScoped()`).

Regarding which scopes, you can find the scopes to be added in this [list](https://developers.google.com/identity/protocols/oauth2/scopes#compute)

And they can be references by these constants: https://github.com/googleapis/google-api-java-client-services/blob/a8f727cf9cc7bb4c173568a09ba477a0d600209a/clients/google-api-services-compute/v1/2.0.0/com/google/api/services/compute/ComputeScopes.java#L24

Going to close this issue as there hasn't been a response in a while, but feel free to re-open if there are any other issues or questions. Thanks!
